services:

  db:
    image: postgres:15-alpine
    container_name: crm_postgres
    restart: always
    environment:
      POSTGRES_DB: crm_db
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d crm_db"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm_app
    restart: always
    ports:
      - "8080:8080"
    environment:
      DB_URL: jdbc:postgresql://db:5432/crm_db
      DB_USERNAME: ${DB_USERNAME}       # ← было POSTGRES_USER
      DB_PASSWORD: ${DB_PASSWORD}       # ← было POSTGRES_PASSWORD
      JWT_SECRET: ${JWT_SECRET}
      FIREBASE_CREDENTIALS_PATH: firebase-service-account.json
      FIREBASE_PROJECT_ID: dummy
    depends_on:
      db:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: crm_pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@crm.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - db
    profiles:
      - dev

volumes:
  postgres_data: