spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/crm_db
    username: YOUR_DB_USERNAME
    password: YOUR_DB_PASSWORD

jwt:
  secret: YOUR_BASE64_JWT_SECRET
  access-token-expiration: 86400000
  refresh-token-expiration: 604800000

firebase:
  credentials-path: firebase-service-account.json
  project-id: YOUR_FIREBASE_PROJECT_ID
